# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRMPipeline-conn'
    subscriptionId: '94df0585-8d4a-455a-b6bb-cfcba4811ce5'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMPipeline-rg'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sw-lyons/Automateio-AzureRM-Pipeline/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName demoARM'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
